name: shopmatcher
description: "A comprehensive price comparison app for shopping across multiple platforms."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^5.8.0
  image_picker: ^1.0.7
  http: ^1.2.1
  http_parser: ^4.0.2
  path_provider: ^2.1.2
  modal_progress_hud_nsn: ^0.4.0
  easy_search_bar: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/